/**
 * Ravimoshark Task API
 * This is an API to interact with Ravimoshark task database. # Introduction This API allow to create, modify and delete task, visits, technicians and interventions. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of task.
 */
export type TaskTypes = 'CANCELLATION' | 'CHANGE_PIECE' | 'STOP_PARTIAL' | 'STOP_TOTAL' | 'PROBLEM_RESULT' | 'UNKNOWN';

export const TaskTypes = {
    CANCELLATION: 'CANCELLATION' as TaskTypes,
    CHANGEPIECE: 'CHANGE_PIECE' as TaskTypes,
    STOPPARTIAL: 'STOP_PARTIAL' as TaskTypes,
    STOPTOTAL: 'STOP_TOTAL' as TaskTypes,
    PROBLEMRESULT: 'PROBLEM_RESULT' as TaskTypes,
    UNKNOWN: 'UNKNOWN' as TaskTypes
};