/**
 * Ravimoshark Task API
 * This is an API to interact with Ravimoshark task database. # Introduction This API allow to create, modify and delete task, visits, technicians and interventions. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { CustomError } from '../model/customError';
import { Deleted } from '../model/deleted';
import { Finished } from '../model/finished';
import { IdInteger } from '../model/idInteger';
import { InlineResponse2001 } from '../model/inlineResponse2001';
import { Tasks } from '../model/tasks';


import { Configuration }                                     from '../configuration';


export interface TasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Add one task.
    * Add one task.
    * @param body 
    */
    addTask(body: Tasks, extraHttpRequestParams?: any): Observable<Tasks>;

    /**
    * Delete one task.
    * Delete one task.
    * @param id id to delete or search
    */
    deleteTask(id: number, extraHttpRequestParams?: any): Observable<IdInteger>;

    /**
    * Edit one task.
    * Edit one task.
    * @param body 
    */
    editTask(body: Tasks, extraHttpRequestParams?: any): Observable<Tasks>;

    /**
    * Get one task.
    * Get one task.
    * @param id id to delete or search
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    */
    getTaskById(id: number, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Tasks>;

    /**
    * Get all tasks.
    * Get all tasks.
    * @param skip number of item to skip
    * @param limit max records to return
    * @param orderBy order by property.
    * @param filterBy filter data.
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    * @param metadata If metadata is needed (for pagination controls)
    * @param refClient Data from a desired client
    * @param finished Get all, finished or unfinished task. Default not finished.
    * @param technicianId Id from a desired technician
    * @param dateFixFrom Date fix from
    * @param dateCallUntil Date call until
    * @param dateCallFrom Date call from
    * @param dateFixUntil Date fix until
    */
    getTasks(skip?: number, limit?: number, orderBy?: string, filterBy?: string, deleted?: Deleted, metadata?: boolean, refClient?: string, finished?: Finished, technicianId?: number, dateFixFrom?: string, dateCallUntil?: string, dateCallFrom?: string, dateFixUntil?: string, extraHttpRequestParams?: any): Observable<InlineResponse2001>;

}
