/**
 * Ravimoshark Task API
 * This is an API to interact with Ravimoshark task database. # Introduction This API allow to create, modify and delete task, visits, technicians and interventions. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { CustomError } from '../model/customError';
import { Deleted } from '../model/deleted';
import { IdInteger } from '../model/idInteger';
import { InlineResponse2001 } from '../model/inlineResponse2001';
import { Technicians } from '../model/technicians';


import { Configuration }                                     from '../configuration';


export interface TechniciansServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Add one technician.
    * Add one technician.
    * @param body 
    */
    addTechnician(body: Technicians, extraHttpRequestParams?: any): Observable<Technicians>;

    /**
    * Delete one technician.
    * Delete one technician.
    * @param id id to delete or search
    */
    deleteTechnician(id: number, extraHttpRequestParams?: any): Observable<IdInteger>;

    /**
    * Edit one technician.
    * Edit one technician.
    * @param body 
    */
    editTechnician(body: Technicians, extraHttpRequestParams?: any): Observable<Technicians>;

    /**
    * Get one technician.
    * Get one technician.
    * @param id id to delete or search
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    */
    getTechnicianById(id: number, deleted?: Deleted, extraHttpRequestParams?: any): Observable<Technicians>;

    /**
    * Get all technicians.
    * Get all technicians.
    * @param skip number of item to skip
    * @param limit max records to return
    * @param orderBy order by property.
    * @param filterBy filter data.
    * @param deleted Get all, deleted, not deleted data. Default not deleted.
    * @param metadata If metadata is needed (for pagination controls)
    * @param refClient Data from a desired contract
    */
    getTechnicians(skip?: number, limit?: number, orderBy?: string, filterBy?: string, deleted?: Deleted, metadata?: boolean, refClient?: string, extraHttpRequestParams?: any): Observable<InlineResponse2001>;

}
